services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Priorist\EdmTypo3\:
    resource: "../Classes/*"
    exclude: "../Classes/Domain/Model/*"

  edm.client:
    class: 'Priorist\EDM\Client\Client'
    factory:
      - 'Priorist\EdmTypo3\Factory\EdmClientFactory'
      - "create"
    arguments:
      - "client"

  Priorist\EdmTypo3\Controller\EventController:
    public: true
    arguments:
      - "@edm.client"
