services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Priorist\EdmTypo3\:
    resource: "../Classes/*"

  Priorist\EdmTypo3\Controller\EventController:
    public: true

  Priorist\EdmTypo3\Controller\EnrollmentController:
    public: true

  Priorist\EdmTypo3\Controller\FormErrorController:
    public: true

  Priorist\EdmTypo3\Controller\LecturerController:
    public: true

  Priorist\EdmTypo3\Controller\LocationController:
    public: true

  Priorist\EdmTypo3\Controller\StaffController:
    public: true

  Priorist\EdmTypo3\ViewHelpers\ImageViewHelper:
    arguments:
      $resourceFactory: '@TYPO3\CMS\Core\Resource\ResourceFactory'
      $imageService: '@TYPO3\CMS\Extbase\Service\ImageService'
